// Code generated by protoc-gen-go-proto-json. DO NOT EDIT.
package example

import (
	"fmt"
	"reflect"

	"google.golang.org/grpc/encoding"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type ProtoJsonCodec struct {
	protojson.MarshalOptions
	protojson.UnmarshalOptions
}

func init() {
	encoding.RegisterCodec(ProtoJsonCodec{})
}

func RegisterProtoJson(m protojson.MarshalOptions, u protojson.UnmarshalOptions) {
	encoding.RegisterCodec(ProtoJsonCodec{m, u})
}

func (c ProtoJsonCodec) Marshal(v interface{}) ([]byte, error) {
	if vv, ok := v.([]byte); ok {
		return vv, nil
	}
	vv, ok := v.(proto.Message)
	if !ok {
		return nil, fmt.Errorf("failed to marshal, message is %T, want proto.Message", v)
	}
	return c.MarshalOptions.Marshal(vv)
}

func (c ProtoJsonCodec) Unmarshal(data []byte, v interface{}) error {
	if _, ok := v.(*[]byte); ok {
		reflect.ValueOf(v).Elem().SetBytes(data)
		return nil
	}
	vv, ok := v.(proto.Message)
	if !ok {
		return fmt.Errorf("failed to unmarshal, message is %T, want proto.Message", v)
	}
	return c.UnmarshalOptions.Unmarshal(data, vv)
}

func (c ProtoJsonCodec) Name() string {
	return "example_codec"
}
