// Code generated by protoc-gen-go-proto-json. DO NOT EDIT.

package example

import (
	"google.golang.org/grpc/encoding"
)

// MarshalJSON implements json.Marshaler
func (msg *Example) MarshalJSON() ([]byte, error) {
	return encoding.GetCodec("example_codec").Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Example) UnmarshalJSON(b []byte) error {
	return encoding.GetCodec("example_codec").Unmarshal(b, msg)
}
